language: generic
addons:
  apt:
    sources:
      - kalakris-cmake
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6
      - cmake
      - cmake-data
before_script:
  - cmake .
  - make
script:
  - ctest
notifications:
  email: false
